# Cloud Build configuration for Compass Next.js application
# This file defines the build steps for Google Cloud Build

steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
    id: 'install-dependencies'
  
  # Step 2: Build the Next.js application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    id: 'build-application'
    waitFor: ['install-dependencies']

# Build timeout (default is 10 minutes, extended for npm install and Next.js build)
timeout: '1200s'

# Options for the build
options:
  logging: CLOUD_LOGGING_ONLY
