# Cloud Build configuration for Compass Next.js application
# This file defines the build steps for Google Cloud Build

steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
    id: 'install-dependencies'
  
  # Step 2: Build the Next.js application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    id: 'build-application'
    waitFor: ['install-dependencies']

# Store the build artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/artifacts'
    paths:
      - '.next/**'
      - 'package.json'
      - 'next.config.mjs'

# Build timeout (default is 10 minutes, increasing for larger builds)
timeout: '1200s'

# Options for the build
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
